# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
Supplier.create(name: "BAUER", email: "sale@bauer.com", phone_number: "888-509-6875")
Supplier.create(name: "WARRIOR", email: "sale@warrior.com", phone_number: "800-9687845")

Product.create(supplier_id: 1, name: "BAUER VAPOR 1X ICE SKATES - 2017 [SENIOR]", price: "949.99", image_id: 1, image: "https://images.purehockey.com/img.aspx?pic_id=108888&pic_type=5", description: "The 1X is constructed using Bauer’s lasted 3D Curv Composite with X-Rib pattern and Comfort Edge padding.")
Product.create(supplier_id: 1, name: "BAUER SUPREME S190 HOCKEY SHIN GUARDS - 2017 [SENIOR]", price: "109.99", image_id: 2, image: "https://images.purehockey.com/img.aspx?itm_id=26681&div_id=41&pic_type=5&mtx_id=0", description: "The S190 Shin guard come complete with a thermoformed, ribbed shin cap to provide elite protection with expert mobility.")
Product.create(supplier_id: 1, name: "BAUER VAPOR 1X PLAYER PANTS [SENIOR]", price: "209.99", image_id: 3, image: "https://images.purehockey.com/img.aspx?pic_id=96099&pic_type=5", description: "Bauer Vapor 1X Sr. Hockey Pants is the ultimate in mobility, the 1X Pants from Bauer have seen some serious upgrades.")
Product.create(supplier_id: 1, name: "BAUER SUPREME S190 HOCKEY SHOULDER PADS - 2017 [SENIOR]", price: "129.99", image_id: 4, image: "https://images.purehockey.com/img.aspx?itm_id=26707&div_id=41&pic_type=5&mtx_id=0", description: "The Bauer Supreme S190 shoulder pads are Bauer's latest release in their Supreme line.")
Product.create(supplier_id: 1, name: "BAUER SUPREME 1S HOCKEY ELBOW PADS - 2017 [SENIOR]", price: "149.99", image_id: 5, image: "https://images.purehockey.com/img.aspx?itm_id=26713&div_id=41&pic_type=5&mtx_id=0", description: "Designed specifically for an anatomical fit, the S17 Supreme line from Bauer is engineered from the inside out, using specially placed material to provide the player with a comfortable, natural fit.")
Product.create(supplier_id: 1, name: "BAUER SUPREME 1S HOCKEY GLOVES - 2017 [SENIOR]", price: "199.99", image_id: 6, image: "https://www.purehockey.com/product/Supreme_1S_Hockey_Gloves_-_2017/itm/26731-41/?mtx_id=0", description: "The Bauer Supreme 1S Hockey Gloves are silky smooth and offer elite level protection.")
Product.create(supplier_id: 2, name: "WARRIOR ALPHA QX3 GRIP COMPOSITE HOCKEY STICK [SENIOR]", price: "149.99", image_id: 7, image: "https://images.purehockey.com/img.aspx?pic_id=107935&pic_type=5", description: "The word alpha is typically used to describe dominance, and that's exactly what you're getting in this stick. The newest and most revolutionary feature of the QX Pro Stick is the Quick Strike technology.")

Image.create(url1: "https://images.purehockey.com/img.aspx?pic_id=108888&pic_type=5", url2: "https://images.purehockey.com/img.aspx?pic_id=107487&pic_type=5", url3: "https://images.purehockey.com/img.aspx?pic_id=108817&pic_type=5")
Image.create(url1: "https://images.purehockey.com/img.aspx?itm_id=26681&div_id=41&pic_type=5&mtx_id=0", url2: "" , url3: "")
Image.create(url1: "https://images.purehockey.com/img.aspx?pic_id=96099&pic_type=5", url2: "https://images.purehockey.com/img.aspx?pic_id=96100&pic_type=5" , url3: "https://images.purehockey.com/img.aspx?pic_id=96102&pic_type=5")
